version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Flask Configuration
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      # Database credentials (from your hosted database)
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      # Application secrets
      - SECRET_KEY=${SECRET_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      # Google Drive Integration
      - FOLDER_ID=${FOLDER_ID}
      - GOOGLE_TYPE=${GOOGLE_TYPE}
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - GOOGLE_PRIVATE_KEY_ID=${GOOGLE_PRIVATE_KEY_ID}
      - GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY}
      - GOOGLE_CLIENT_EMAIL=${GOOGLE_CLIENT_EMAIL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_AUTH_URI=${GOOGLE_AUTH_URI}
      - GOOGLE_TOKEN_URI=${GOOGLE_TOKEN_URI}
      - GOOGLE_AUTH_PROVIDER_X509_CERT_URL=${GOOGLE_AUTH_PROVIDER_X509_CERT_URL}
      - GOOGLE_CLIENT_X509_CERT_URL=${GOOGLE_CLIENT_X509_CERT_URL}
      - GOOGLE_UNIVERSE_DOMAIN=${GOOGLE_UNIVERSE_DOMAIN}
    volumes:
      - .:/app
      - /app/__pycache__
      - ./temp:/app/temp
    working_dir: /app
    restart: unless-stopped